test_that("calcPhasogram() and estimateNRL() work properly", {
    bamf <- system.file("extdata", "phasograms", "mnase_mm10.bam", package = "swissknife")
    pg1 <- calcPhasogram(bamf)
    pg2 <- calcPhasogram(bamf, rmdup = FALSE)
    pg3 <- calcPhasogram(c(bamf,bamf))
    pg4 <- calcPhasogram(bamf, regions = GenomicRanges::GRanges("chr10", IRanges::IRanges(start = 19000000, end = 23000000)))
    pg5 <- calcPhasogram(bamf, regions = GenomicRanges::GRanges("chr11", IRanges::IRanges(start = 19000000, end = 23000000)))
    expect_true(is.numeric(pg1))
    expect_length(pg1, 3000L)
    expect_true(all(pg2 > pg1))
    expect_equal(pg1, pg3)
    expect_equal(pg1, pg4)
    expect_true(sum(pg5) == 0L)

    nrl <- estimateNRL(pg1, usePeaks = 1:4)
    expect_true(is.list(nrl))
    expect_equal(nrl$nrl, 186.4)
    expect_length(nrl$nrl.CI95, 2L)
})
